# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example/proto/greeter.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x65xample/proto/greeter.proto\x12\x07greeter\"\"\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\"&\n\nHelloReply\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2C\n\x07Greeter\x12\x38\n\x08SayHello\x12\x15.greeter.HelloRequest\x1a\x13.greeter.HelloReply\"\x00\x42l\n\x18io.grpc.examples.GreeterB\x0cGreeterProtoP\x01Z:github.com/rules-proto-grpc/rules_proto_grpc/example/proto\xa2\x02\x03GTRb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'example.proto.greeter_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\n\030io.grpc.examples.GreeterB\014GreeterProtoP\001Z:github.com/rules-proto-grpc/rules_proto_grpc/example/proto\242\002\003GTR'
  _HELLOREQUEST._serialized_start=40
  _HELLOREQUEST._serialized_end=74
  _HELLOREPLY._serialized_start=76
  _HELLOREPLY._serialized_end=114
  _GREETER._serialized_start=116
  _GREETER._serialized_end=183
# @@protoc_insertion_point(module_scope)
